title: "Dzmitryi Kharlanau | System Analyst & SAP Transformation Consultant"
description: "System Analyst & SAP Transformation Consultant — senior SAP solution leader with 12+ years across Order-to-Cash, logistics, and data; modernizing S/4HANA landscapes, orchestrating integrations, and enabling intelligent automation."
theme: minima
url: "https://dkharlanau.github.io"
baseurl: ""
permalink: pretty
lang: en
author:
  name: "Dzmitryi Kharlanau"
  title: "System Analyst & SAP Transformation Consultant"
  bio: "System analyst with 12+ years shaping SAP S/4HANA transformations, stabilizing global processes, and building integration-first automation that delivers measurable business impact."
twitter:
  username: dkharlanau
social:
  name: "Dzmitryi Kharlanau"
  links:
    - "https://www.linkedin.com/in/dkharlanau"
    - "https://hashnode.com/@dkharlanau"
    - "https://medium.com/@dkharlanau"
    - "https://www.reddit.com/user/dkharlanau"
    - "https://x.com/dkharlanau"
    - "https://huggingface.co/dkharlanau"
    - "https://dev.to/dkharlanau"
    - "https://substack.com/@dkharlanau"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  notes:
    output: true
    permalink: /notes/:slug/
defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note
exclude:
  - scripts
  - tests
  - Complete_LinkedIn
  - .gitignore
  - .github
  - README.md
  - LICENSE
  - vendor
sass:
  style: compressed
include:
  - LLM.txt
