title: "Dzmitryi Kharlanau | SAP Order-to-Cash Lead"
description: "Senior SAP S/4HANA Order-to-Cash consultant helping enterprises modernize operations, integrate ecosystems, and automate with intelligence."
theme: minima
url: "https://dkharlanau.github.io"
baseurl: ""
permalink: pretty
lang: en
author:
  name: "Dzmitryi Kharlanau"
  title: "Senior SAP Order-to-Cash Consultant"
  bio: "SAP S/4HANA Order-to-Cash specialist focused on resilient integrations, analytics-ready data, and automation that drives measurable business impact."
twitter:
  username: dkharlanau
social:
  name: "Dzmitryi Kharlanau"
  links:
    - "https://www.linkedin.com/in/dkharlanau"
    - "https://hashnode.com/@dkharlanau"
    - "https://medium.com/@dkharlanau"
    - "https://www.reddit.com/user/dkharlanau"
    - "https://x.com/dkharlanau"
    - "https://huggingface.co/dkharlanau"
    - "https://dev.to/dkharlanau"
    - "https://substack.com/@dkharlanau"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
collections:
  notes:
    output: true
    permalink: /notes/:slug/
defaults:
  - scope:
      path: ""
      type: notes
    values:
      layout: note
exclude:
  - scripts
  - tests
  - Complete_LinkedIn
  - .gitignore
  - .github
  - README.md
  - LICENSE
sass:
  style: compressed
include:
  - LLM.txt
