#!/usr/bin/env python3
"""
Professional Radar Closeout Report

Generates a formatted closeout report summarizing a Product Radar run.
Can be used manually with CLI args or read from a JSON state file.

Usage:
  # With CLI arguments
  python3 professional-radar/scripts/professional_radar_closeout.py \
    --sources-checked 5 \
    --signals-discovered 12 \
    --signals-accepted 8 \
    --signals-rejected 4 \
    --site-files-created 3 \
    --validation-passed yes \
    --next-actions "Review LinkedIn drafts, update atlas index"

  # With state file (JSON from a previous run)
  python3 professional-radar/scripts/professional_radar_closeout.py \
    --state-file /tmp/radar-run-state.json

  # Dry-run / template mode
  python3 professional-radar/scripts/professional_radar_closeout.py --template
"""

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path


def format_report(
    run_date: str,
    sources_checked: int,
    signals_discovered: int,
    signals_accepted: int,
    signals_rejected: int,
    site_files_created: int,
    validation_passed: str,
    next_actions: str,
    run_id: str = None,
    branch: str = None,
    commit: str = None,
) -> str:
    """Generate a formatted closeout report."""
    lines = [
        "# Product Radar Closeout Report",
        "",
        f"- **Run date:** {run_date}",
    ]

    if run_id:
        lines.append(f"- **Run ID:** {run_id}")
    if branch:
        lines.append(f"- **Branch:** {branch}")
    if commit:
        lines.append(f"- **Commit:** {commit}")

    lines.extend([
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Sources checked | {sources_checked} |",
        f"| Signals discovered | {signals_discovered} |",
        f"| Signals accepted | {signals_accepted} |",
        f"| Signals rejected | {signals_rejected} |",
        f"| Site files created | {site_files_created} |",
        f"| Validation passed | {validation_passed} |",
        "",
        "## Next actions",
        "",
        f"{next_actions}",
        "",
        "---",
        "",
        "*Generated by Professional Radar Closeout Report*",
    ])

    return "\n".join(lines)


def parse_state_file(path: Path) -> dict:
    """Read a JSON state file from a previous radar run."""
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data


def main():
    parser = argparse.ArgumentParser(
        description="Generate a Product Radar closeout report"
    )
    parser.add_argument("--run-date", type=str, default=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
                        help="Run date (default: now)")
    parser.add_argument("--run-id", type=str, default=None,
                        help="Optional run identifier")
    parser.add_argument("--branch", type=str, default=None,
                        help="Git branch used for this run")
    parser.add_argument("--commit", type=str, default=None,
                        help="Git commit hash")
    parser.add_argument("--sources-checked", type=int, default=0,
                        help="Number of sources checked")
    parser.add_argument("--signals-discovered", type=int, default=0,
                        help="Number of signals discovered")
    parser.add_argument("--signals-accepted", type=int, default=0,
                        help="Number of signals accepted")
    parser.add_argument("--signals-rejected", type=int, default=0,
                        help="Number of signals rejected")
    parser.add_argument("--site-files-created", type=int, default=0,
                        help="Number of site files created")
    parser.add_argument("--validation-passed", type=str, default="unknown",
                        help="Validation result: yes/no/partial/unknown")
    parser.add_argument("--next-actions", type=str, default="None",
                        help="Comma-separated or free-text next actions")
    parser.add_argument("--state-file", type=str, default=None,
                        help="Path to JSON state file from a previous run")
    parser.add_argument("--template", action="store_true",
                        help="Print a template report with zero values")
    parser.add_argument("--output", type=str, default=None,
                        help="Write report to file instead of stdout")

    args = parser.parse_args()

    # If state file provided, load it and override defaults
    if args.state_file:
        state = parse_state_file(Path(args.state_file))
        run_date = state.get("run_date", args.run_date)
        run_id = state.get("run_id", args.run_id)
        branch = state.get("branch", args.branch)
        commit = state.get("commit", args.commit)
        sources_checked = state.get("sources_checked", args.sources_checked)
        signals_discovered = state.get("signals_discovered", args.signals_discovered)
        signals_accepted = state.get("signals_accepted", args.signals_accepted)
        signals_rejected = state.get("signals_rejected", args.signals_rejected)
        site_files_created = state.get("site_files_created", args.site_files_created)
        validation_passed = state.get("validation_passed", args.validation_passed)
        next_actions = state.get("next_actions", args.next_actions)
    else:
        run_date = args.run_date
        run_id = args.run_id
        branch = args.branch
        commit = args.commit
        sources_checked = args.sources_checked
        signals_discovered = args.signals_discovered
        signals_accepted = args.signals_accepted
        signals_rejected = args.signals_rejected
        site_files_created = args.site_files_created
        validation_passed = args.validation_passed
        next_actions = args.next_actions

    report = format_report(
        run_date=run_date,
        sources_checked=sources_checked,
        signals_discovered=signals_discovered,
        signals_accepted=signals_accepted,
        signals_rejected=signals_rejected,
        site_files_created=site_files_created,
        validation_passed=validation_passed,
        next_actions=next_actions,
        run_id=run_id,
        branch=branch,
        commit=commit,
    )

    if args.output:
        output_path = Path(args.output)
        output_path.write_text(report, encoding="utf-8")
        print(f"Report written to: {output_path}")
    else:
        print(report)


if __name__ == "__main__":
    main()
