#!/usr/bin/env python3
"""
Professional Radar Validator

Validates radar and news content for quality, correctness, and safety.

Checks:
- Frontmatter completeness (required fields)
- Confidence level (reject low, warn on medium)
- Content quality (key points, practical impact, source attribution)
- File naming conventions (YYYY-MM-DD-slug.md)
- No sample/draft files in production collections
- No SAMPLE/DRAFT markers in published content
- Atlas topic routing (optional)

Stages:
  site   — content validation only (fast)
  build  — content + Jekyll build (slower, requires Ruby/Jekyll)

Usage:
  python3 professional-radar/scripts/professional_radar_validate.py --all --stage site
  python3 professional-radar/scripts/professional_radar_validate.py --all --stage build
  python3 professional-radar/scripts/professional_radar_validate.py --radar-dir _radar --strict
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: PyYAML is required. Install: pip install pyyaml")
    sys.exit(1)

# --- Paths ---
REPO_ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_RADAR_DIR = REPO_ROOT / "_radar"
DEFAULT_NEWS_DIR = REPO_ROOT / "_news"
ATLAS_INDEX_PATH = REPO_ROOT / "_data" / "atlas_index.yml"

# --- Config ---
RADAR_REQUIRED_FIELDS = {"layout", "title", "date", "source", "source_url", "confidence", "topics"}
NEWS_REQUIRED_FIELDS = {"layout", "title", "date", "source", "source_url", "confidence", "topics", "permalink"}
CONFIDENCE_ALLOWED = {"high", "medium", "low"}
FILENAME_PATTERN = re.compile(r"^\d{4}-\d{2}-\d{2}-[a-z0-9-]+\.md$")


def fail(msg: str, strict: bool = False) -> bool:
    label = "ERROR" if strict else "WARN"
    print(f"  [{label}] {msg}")
    return strict


def ok(msg: str):
    print(f"  [OK]  {msg}")


def info(msg: str):
    print(f"  [INFO] {msg}")


def extract_frontmatter(filepath: Path) -> tuple:
    """Extract and parse YAML frontmatter from a markdown file.
    Returns (frontmatter_dict, body_text, error_string).
    """
    text = filepath.read_text(encoding="utf-8")

    if not text.startswith("---"):
        return None, text, "missing front matter"

    parts = text.split("---", 2)
    if len(parts) < 3:
        return None, text, "invalid front matter structure"

    try:
        front = yaml.safe_load(parts[1])
        if not isinstance(front, dict):
            return None, parts[2], "front matter is not a dict"
        return front, parts[2], None
    except yaml.YAMLError as e:
        return None, text, f"invalid YAML: {e}"


def check_collection_dir(dir_path: Path, required_fields: set, strict: bool = False) -> bool:
    """Validate all .md files in a collection directory."""
    if not dir_path.exists():
        info(f"Directory not found: {dir_path}")
        return False

    md_files = sorted(dir_path.glob("*.md"))
    # Skip index files if any
    md_files = [f for f in md_files if f.name != "index.md"]

    if not md_files:
        info(f"No .md items in {dir_path}")
        return False

    ok(f"Found {len(md_files)} item(s) in {dir_path}")
    errors = 0

    for filepath in md_files:
        front, body, error = extract_frontmatter(filepath)

        if error:
            errors += fail(f"{filepath.name}: {error}", strict)
            continue

        # Check required fields
        missing = required_fields - set(front.keys())
        if missing:
            errors += fail(f"{filepath.name}: missing {', '.join(sorted(missing))}", strict)

        # Check confidence
        confidence = front.get("confidence", "medium")
        if confidence not in CONFIDENCE_ALLOWED:
            errors += fail(f"{filepath.name}: invalid confidence '{confidence}'", strict)
        elif confidence == "low":
            errors += fail(f"{filepath.name}: confidence 'low' — should not be published", strict)
        elif confidence == "medium":
            info(f"{filepath.name}: confidence 'medium' — review recommended")

        # Check topics
        topics = front.get("topics", [])
        if not topics:
            errors += fail(f"{filepath.name}: no topics", strict)
        elif not isinstance(topics, list):
            errors += fail(f"{filepath.name}: topics must be a list", strict)

        # Check body sections
        if "**Key points:**" not in body:
            errors += fail(f"{filepath.name}: missing 'Key points' section", strict)
        if "**Practical impact:**" not in body:
            errors += fail(f"{filepath.name}: missing 'Practical impact' section", strict)
        if "*Source:" not in body:
            errors += fail(f"{filepath.name}: missing source attribution", strict)
        if "Generated by Professional Radar" not in body:
            errors += fail(f"{filepath.name}: missing 'Generated by Professional Radar' footer", strict)

        # Check for sample/draft markers in production
        lower_name = filepath.name.lower()
        if "sample" in lower_name or "draft" in lower_name:
            errors += fail(f"{filepath.name}: sample/draft filename not allowed in production", strict)
        if "SAMPLE" in body or "DRAFT" in body.upper():
            errors += fail(f"{filepath.name}: contains SAMPLE/DRAFT marker", strict)

        # Check filename format
        if not FILENAME_PATTERN.match(filepath.name):
            errors += fail(f"{filepath.name}: filename must match YYYY-MM-DD-slug.md", strict)

    return errors > 0


def check_atlas_routing(strict: bool = False) -> bool:
    """Check that radar topics map to known atlas clusters."""
    if not ATLAS_INDEX_PATH.exists():
        info("Atlas index not found, skipping routing check")
        return False

    try:
        with open(ATLAS_INDEX_PATH, "r", encoding="utf-8") as f:
            data = yaml.safe_load(f)
    except yaml.YAMLError as e:
        return fail(f"Invalid atlas index YAML: {e}", strict)

    clusters = data.get("topic_clusters", [])
    if not clusters:
        return fail("No topic clusters in atlas index", strict)

    # Collect all cluster keywords
    cluster_keywords = set()
    for cluster in clusters:
        keywords = cluster.get("keywords", [])
        cluster_keywords.update(k.lower().strip() for k in keywords)

    # Collect all radar topics
    radar_topics = set()
    if DEFAULT_RADAR_DIR.exists():
        for filepath in DEFAULT_RADAR_DIR.glob("*.md"):
            if filepath.name == "index.md":
                continue
            front, _, error = extract_frontmatter(filepath)
            if error:
                continue
            topics = front.get("topics", [])
            radar_topics.update(t.lower().strip() for t in topics)

    unmapped = radar_topics - cluster_keywords
    if unmapped:
        info(f"Unmapped radar topics (may need atlas update): {', '.join(sorted(unmapped))}")
    else:
        ok("All radar topics map to atlas clusters")

    return False


def run_jekyll_build(strict: bool = False) -> bool:
    """Run Jekyll build and report results."""
    print("\n== Running Jekyll build ==")
    try:
        result = subprocess.run(
            ["bundle", "exec", "jekyll", "build"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        ok("Jekyll build succeeded")
        return False
    except subprocess.CalledProcessError as e:
        return fail(f"Jekyll build failed:\n{e.stderr}", strict=True)
    except FileNotFoundError:
        return fail("bundle/jekyll not found — is Ruby/Jekyll installed?", strict=True)


def main():
    parser = argparse.ArgumentParser(
        description="Validate Professional Radar site content"
    )
    parser.add_argument("--all", action="store_true",
                        help="Run all validation checks")
    parser.add_argument("--stage", choices=["site", "build"],
                        help="Validation stage: site (content) or build (content + Jekyll)")
    parser.add_argument("--strict", action="store_true",
                        help="Treat warnings as errors (exit non-zero)")
    parser.add_argument("--radar-dir", type=str, default=str(DEFAULT_RADAR_DIR),
                        help="Radar directory to validate")
    parser.add_argument("--news-dir", type=str, default=str(DEFAULT_NEWS_DIR),
                        help="News directory to validate")

    args = parser.parse_args()

    print("Professional Radar Validator")
    print(f"Repo root: {REPO_ROOT}")
    print(f"Stage:     {args.stage or 'site'}")
    print(f"Strict:    {args.strict}")

    failed = False

    # Content validation (always run unless overridden)
    if args.all or not args.stage or args.stage in ("site", "build"):
        print("\n== Validating _radar/ ==")
        failed |= check_collection_dir(Path(args.radar_dir), RADAR_REQUIRED_FIELDS, strict=args.strict)

        print("\n== Validating _news/ ==")
        failed |= check_collection_dir(Path(args.news_dir), NEWS_REQUIRED_FIELDS, strict=args.strict)

        print("\n== Validating atlas routing ==")
        failed |= check_atlas_routing(strict=args.strict)

    # Build validation
    if args.stage == "build" or (args.all and not args.stage):
        failed |= run_jekyll_build(strict=args.strict)

    # Summary
    print("\n" + "=" * 50)
    print("Summary")
    print("=" * 50)
    if failed:
        print("Result: FAILED")
        sys.exit(1)
    else:
        print("Result: PASSED")
        sys.exit(0)


if __name__ == "__main__":
    main()
