#!/usr/bin/env python3
"""
Generate Update Patch — patch-style update for existing _radar/_notes notes.

When the related content resolver returns `update_existing`, this script
generates a patch that adds a new "Update" section to an existing note
without overwriting the original content.

Usage:
    python3 scripts/generate_update_patch.py \
        --note _radar/2026-05-30-finding-the-needle-ai-assisted-debugging.md \
        --signal '{"title":"AI-Assisted Debugging Update","source":"SAP Blog","source_url":"https://example.com/update","summary":"New developments...","key_points":["Point 1","Point 2"],"practical_impact":"This changes..."}' \
        --output /tmp/patched_note.md
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def parse_frontmatter(text: str) -> tuple[dict, str]:
    """Parse YAML frontmatter and return (frontmatter_dict, body_text)."""
    match = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.DOTALL)
    if not match:
        return {}, text

    try:
        import yaml
    except ImportError:
        print("ERROR: PyYAML required. Install: pip install pyyaml", file=sys.stderr)
        sys.exit(1)

    try:
        frontmatter = yaml.safe_load(match.group(1)) or {}
    except yaml.YAMLError:
        frontmatter = {}

    body = match.group(2)
    return frontmatter, body


def dump_frontmatter(frontmatter: dict) -> str:
    """Dump frontmatter dict to YAML string."""
    try:
        import yaml
    except ImportError:
        print("ERROR: PyYAML required.", file=sys.stderr)
        sys.exit(1)

    yaml_str = yaml.dump(
        frontmatter,
        allow_unicode=True,
        sort_keys=False,
        default_flow_style=False,
        width=120,
    )
    return f"---\n{yaml_str}---\n"


def extract_disclaimer(body: str) -> tuple[str, str]:
    """Extract the source/disclaimer footer from body. Returns (main_body, footer)."""
    lines = body.split("\n")
    footer_start = None
    for i in range(len(lines) - 1, -1, -1):
        line = lines[i]
        if line.startswith("*Source:") or line.startswith("*Generated by"):
            footer_start = i
            break
    if footer_start is None:
        return body, ""

    main_body = "\n".join(lines[:footer_start]).rstrip()
    footer = "\n".join(lines[footer_start:])
    return main_body, footer


def generate_update_section(signal: dict) -> str:
    """Generate an Update section in Author Voice v6 format."""
    title = signal.get("title", "Update")
    source = signal.get("source", "")
    source_url = signal.get("source_url", "")
    summary = signal.get("summary", "")
    key_points = signal.get("key_points", [])
    practical_impact = signal.get("practical_impact", "")
    confidence = signal.get("confidence", "medium")

    lines = [f"\n---\n\n**Update — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}**\n"]
    lines.append(f"*{title}* (confidence: {confidence})\n")

    if summary:
        lines.append(f"{summary}\n")

    if key_points:
        lines.append("**Key points:**\n")
        for point in key_points:
            lines.append(f"- {point}")
        lines.append("")

    if practical_impact:
        lines.append("**Practical impact:**\n")
        lines.append(f"{practical_impact}\n")

    if source_url:
        lines.append(f"*Source: [{source}]({source_url})*\n")
    elif source:
        lines.append(f"*Source: {source}*\n")

    return "\n".join(lines)


def generate_patch(note_path: Path, signal: dict) -> str:
    """Generate a patched note that adds an Update section."""
    text = note_path.read_text(encoding="utf-8")
    frontmatter, body = parse_frontmatter(text)

    # Update frontmatter: add updated_at if not present
    if "updated_at" not in frontmatter:
        frontmatter["updated_at"] = datetime.now(timezone.utc).isoformat()

    # Merge topics from signal if present
    signal_topics = signal.get("topics", [])
    if signal_topics:
        existing_topics = set(frontmatter.get("topics", []))
        merged = list(existing_topics) + [t for t in signal_topics if t not in existing_topics]
        frontmatter["topics"] = merged

    main_body, footer = extract_disclaimer(body)
    update_section = generate_update_section(signal)

    # Assemble: frontmatter + original body + update + footer
    new_body = f"{main_body}{update_section}{footer}"

    return dump_frontmatter(frontmatter) + new_body


def main():
    parser = argparse.ArgumentParser(description="Generate patch update for existing note")
    parser.add_argument("--note", required=True, help="Path to existing _radar/_notes .md file")
    parser.add_argument("--signal", required=True, help="JSON string with signal info")
    parser.add_argument("--output", required=True, help="Output path for patched file")
    args = parser.parse_args()

    note_path = Path(args.note)
    if not note_path.exists():
        print(f"ERROR: Note file not found: {note_path}", file=sys.stderr)
        sys.exit(1)

    try:
        signal = json.loads(args.signal)
    except json.JSONDecodeError as e:
        print(f"ERROR: Invalid JSON in --signal: {e}", file=sys.stderr)
        sys.exit(1)

    patched = generate_patch(note_path, signal)

    output_path = Path(args.output)
    output_path.write_text(patched, encoding="utf-8")
    print(f"Patched note written to: {output_path}")
    print(f"Original: {note_path}")
    print(f"Update title: {signal.get('title', 'N/A')}")


if __name__ == "__main__":
    main()
