#!/usr/bin/env python3
"""
generate_update_patch.py — Update Existing Note Workflow (Issue #41)

When the related content resolver returns `update_existing`, this script
generates a patch-style update to an existing _radar or _notes file.

Rules:
- Preserve existing content (never overwrite)
- Append an "Update" section with new signal info
- Add `updated` to frontmatter if not present
- Use Author Voice v6 format
- PR-first: output to stdout or write to a new file; never blind overwrite

Usage:
    python3 scripts/generate_update_patch.py \
        --note-file _radar/2026-05-30-finding-the-needle-ai-assisted-debugging.md \
        --signal '{"title":"New AI Debugging Feature","source":"SAP","url":"https://...","key_points":["..."]}'

    python3 scripts/generate_update_patch.py \
        --note-file _radar/2026-05-30-finding-the-needle-ai-assisted-debugging.md \
        --title "New AI Debugging Feature" \
        --source "SAP Architecture Center" \
        --url "https://..." \
        --key-points "Faster trace" "New log format"
"""

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def parse_frontmatter(content: str) -> tuple:
    """Extract YAML frontmatter and body from markdown."""
    match = re.match(r'^---\s*\n(.*?)\n---\s*\n(.*)', content, re.DOTALL)
    if not match:
        return None, content
    return match.group(1), match.group(2)


def update_frontmatter(frontmatter_yaml: str, today_iso: str) -> str:
    """Add `updated` field to frontmatter if not present."""
    if 'updated:' in frontmatter_yaml:
        # Replace existing updated date
        frontmatter_yaml = re.sub(
            r'updated:\s*\S+',
            f'updated: {today_iso}',
            frontmatter_yaml
        )
    else:
        # Add updated after date
        frontmatter_yaml = re.sub(
            r'^(date:\s*\S+)',
            rf'\1\nupdated: {today_iso}',
            frontmatter_yaml,
            flags=re.MULTILINE
        )
    return frontmatter_yaml


def format_update_section(signal: dict, today_iso: str) -> str:
    """Format the Update section in Author Voice v6."""
    title = signal.get('title', 'Untitled Update')
    source = signal.get('source', signal.get('source_name', 'Unknown'))
    url = signal.get('url', signal.get('source_url', signal.get('item_url', '')))
    key_points = signal.get('key_points', signal.get('summary', '').split('\n') if signal.get('summary') else [])
    if isinstance(key_points, str):
        key_points = [key_points]

    lines = [
        f"\n---\n\n## Update — {today_iso}\n",
        f"**New signal:** {title}\n",
    ]
    if source:
        lines.append(f"**Source:** {source}\n")
    if url:
        lines.append(f"**URL:** {url}\n")

    if key_points:
        lines.append("**Key points:**\n")
        for point in key_points:
            if point.strip():
                lines.append(f"- {point.strip()}\n")

    # Add practical impact placeholder
    lines.extend([
        "\n**Practical impact:**\n",
        "_[To be written during manual review]_\n",
    ])

    if url:
        lines.append(f"\n*Source: [{source or url}]({url})*\n")

    lines.append("\n*Update generated by Professional Radar — manual review required.*\n")
    return ''.join(lines)


def generate_patch(note_file: Path, signal: dict, output_file: Path = None, dry_run: bool = False) -> str:
    """Generate patch-style update for an existing note."""
    content = note_file.read_text(encoding='utf-8')
    frontmatter_yaml, body = parse_frontmatter(content)

    if frontmatter_yaml is None:
        print(f"ERROR: Could not parse frontmatter in {note_file}", file=sys.stderr)
        sys.exit(1)

    today_iso = datetime.now(timezone.utc).strftime('%Y-%m-%d')
    updated_frontmatter = update_frontmatter(frontmatter_yaml, today_iso)
    update_section = format_update_section(signal, today_iso)

    # Combine: frontmatter + existing body + update section
    new_content = f"---\n{updated_frontmatter}\n---\n{body}{update_section}"

    if dry_run:
        print(new_content)
        return new_content

    if output_file:
        output_file.write_text(new_content, encoding='utf-8')
        print(f"Updated: {output_file}")
    else:
        # Default: write to same file (but we never blind overwrite —
        # this is only called when user explicitly wants to update)
        backup = note_file.with_suffix(note_file.suffix + '.backup')
        backup.write_text(content, encoding='utf-8')
        note_file.write_text(new_content, encoding='utf-8')
        print(f"Updated: {note_file} (backup: {backup})")

    return new_content


def main():
    parser = argparse.ArgumentParser(description="Generate patch-style update for existing radar/note")
    parser.add_argument("--note-file", required=True, help="Path to existing _radar or _notes .md file")
    parser.add_argument("--signal", help="JSON dict with title, source, url, key_points")
    parser.add_argument("--title", help="Signal title")
    parser.add_argument("--source", help="Signal source name")
    parser.add_argument("--url", help="Signal URL")
    parser.add_argument("--key-points", nargs='*', help="Key points as separate args")
    parser.add_argument("--output", help="Output file path (default: overwrite with backup)")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout, do not write")
    args = parser.parse_args()

    note_file = Path(args.note_file)
    if not note_file.exists():
        print(f"ERROR: Note file not found: {note_file}", file=sys.stderr)
        sys.exit(1)

    signal = {}
    if args.signal:
        try:
            signal = json.loads(args.signal)
        except json.JSONDecodeError as e:
            print(f"ERROR: Invalid --signal JSON: {e}", file=sys.stderr)
            sys.exit(1)
    else:
        signal = {
            "title": args.title or "Untitled Update",
            "source": args.source or "",
            "url": args.url or "",
            "key_points": args.key_points or [],
        }

    output_file = Path(args.output) if args.output else None
    generate_patch(note_file, signal, output_file=output_file, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
