// Original synthetic exercises. These rules describe this model, not SAP behaviour.
export const cases = [
  {
    id: 'units', title: 'Ten ordered. One hundred delivered?', category: 'Quantity & units',
    brief: 'A fictional operations report marks an order as over-delivered by 90 units. The coordinator asks you to correct the shipment before billing.',
    objective: 'Determine whether the records show an over-delivery, then choose the smallest supported correction.',
    evidence: [
      { id: 'A', title: 'Order and fulfilment records', intro: 'All three rows refer to the same fictional order line and product. No other shipments or returns exist in this exercise.', columns: ['Record', 'Quantity', 'Unit', 'Meaning'], rows: [['Order line', '10', 'BOX', 'Requested quantity'], ['Shipment', '100', 'EA', 'Confirmed quantity shipped'], ['Billing draft', '10', 'BOX', 'Quantity proposed for billing']] },
      { id: 'B', title: 'Product conversion rule', intro: 'This conversion was effective when the order, shipment, and draft were created. EA means one individual item.', columns: ['Product', 'Alternate unit', 'Base unit', 'Conversion'], rows: [['Practice product A', 'BOX', 'EA', '1 BOX = 10 EA']] },
      { id: 'C', title: 'Exception report definition', intro: 'The report reads the quantity columns directly. It neither stores the units nor applies a conversion.', columns: ['Field', 'Rule', 'Reported value'], rows: [['Requested', 'Order quantity', '10'], ['Shipped', 'Shipment quantity', '100'], ['Excess', 'Shipped − requested', '90']] }
    ],
    calculation: { label: 'Express the requested quantity in EA', suffix: 'EA', expected: 100, explanation: '10 BOX × 10 EA per BOX = 100 EA. The shipment is also 100 EA; the supported excess is 0 EA.' },
    cause: { label: 'Which conclusion is supported?', correct: 'report', options: [['physical', 'The shipment contains 90 extra items.'], ['master', 'The product conversion is demonstrably wrong.'], ['report', 'The exception report compares different units.']], explanation: 'A and B reconcile the physical quantities. C shows that the report subtracts raw numbers without their units.' },
    citations: { expected: ['A', 'B', 'C'], explanation: 'A supplies the quantities, B defines their relationship, and C proves why the exception is generated. All three support the complete diagnosis.' },
    action: { label: 'What is the next supported action?', correct: 'normalize', options: [['reverse', 'Reverse the shipment to remove 90 items.'], ['normalize', 'Normalize the report quantities using the dated conversion; leave the source records unchanged.'], ['edit', 'Change the order quantity from 10 to 100 BOX.']], explanation: 'There is no evidence for changing the physical or commercial records. The identified defect is in the comparison rule.' },
    verification: { label: 'Which check would test the correction?', correct: 'two', options: [['green', 'Confirm this exception row is now green.'], ['two', 'Test this equal-quantity case and a real excess case after conversion.'], ['hide', 'Hide every row where the document units differ.']], explanation: 'The fix must both clear this false positive and retain a real one: a shipment of 110 EA against the same order must still flag 10 EA excess.' },
    explanation: ['The report found a numeric difference, not a physical excess. Requested, shipped, and draft-billed quantities all represent 100 EA under the supplied rule.', 'Correct the comparison at a common unit and retain the conversion used. Do not rewrite transactional quantities to make a report agree.', 'Outside this model, verify the effective conversion, split shipments, reversals, returns, and whether the report measures cumulative or individual quantities. Those facts are stipulated here.']
  },
  {
    id: 'duplicate', title: 'One dispatch, two inventory postings', category: 'Integration recovery',
    brief: 'A fictional dispatch of 24 EA reduced the inventory ledger by 48 EA. The retry received a successful technical response.',
    objective: 'Trace the business event through the retries. Separate the original posting from the duplicate before choosing a recovery plan.',
    evidence: [
      { id: 'A', title: 'Dispatch and message attempts', intro: 'The source confirms one dispatch. A retry keeps its original event key but receives a new transport attempt identifier.', columns: ['Attempt', 'Business event key', 'Quantity', 'Receiver response'], rows: [['try-1', 'dispatch-alpha', '24 EA', 'Sender timed out waiting'], ['try-2', 'dispatch-alpha', '24 EA', 'Accepted']] },
      { id: 'B', title: 'Receiver posting ledger', intro: 'Inventory immediately before these postings was 200 EA. No other movement occurred in this exercise.', columns: ['Posting', 'Attempt', 'Event key', 'Movement'], rows: [['post-1', 'try-1', 'dispatch-alpha', '−24 EA'], ['post-2', 'try-2', 'dispatch-alpha', '−24 EA']] },
      { id: 'C', title: 'Receiver duplicate rule', intro: 'The simplified receiver checks whether an attempt identifier was already processed. It does not check the business event key.', columns: ['Rule', 'Observed result'], rows: [['Uniqueness key', 'Attempt identifier'], ['try-1 then try-2', 'Different identifiers; both posted'], ['Same event key', 'Not considered by current rule']] }
    ],
    calculation: { label: 'What should inventory be after one dispatch?', suffix: 'EA', expected: 176, explanation: '200 − 24 = 176 EA. The observed ledger is 152 EA because the same business event reduced inventory twice.' },
    cause: { label: 'Which conclusion is supported?', correct: 'key', options: [['two-orders', 'There were two distinct business dispatches.'], ['timeout', 'A sender timeout proves the first attempt did not post.'], ['key', 'The receiver treats a retry as new because it checks the attempt ID.']], explanation: 'A identifies one event, B proves two postings, and C explains why different attempts passed the duplicate check. A timeout did not undo the first posting.' },
    citations: { expected: ['A', 'B', 'C'], explanation: 'Use A to establish the single event, B to confirm its duplicate business effect, and C to identify the faulty uniqueness boundary.' },
    action: { label: 'What is the next supported action?', correct: 'controlled', options: [['retry', 'Replay both successful attempts again.'], ['delete', 'Delete both posting records directly from the ledger.'], ['controlled', 'Stop further replay, confirm the duplicate with the owner, reverse only the duplicate through the approved process, then fix the event-key check.']], explanation: 'Contain further duplicate effects. Recovery must preserve the original valid dispatch and an audit trail. This model does not execute a reversal or prescribe a production transaction.' },
    verification: { label: 'Which test checks the new duplicate rule?', correct: 'replay-new', options: [['replay-new', 'Replay the same event under a new attempt ID, then send a genuinely new event.'], ['status', 'Check that the receiver returns a success response.'], ['block-all', 'Reject every subsequent message for the same product.']], explanation: 'A repeated event must produce no extra inventory movement; a different event must still post. Merely accepting or rejecting all messages is insufficient.' },
    explanation: ['A transport response describes an attempt. The inventory ledger records a business effect. Here the first effect completed even though the sender did not receive its acknowledgement.', 'The duplicate boundary belongs around a durable business event key in this model. Checking attempt IDs allows a retried event to pass as new.', 'In a real integration, establish the event-key scope, concurrent retries, commit behaviour, reversal ownership, and recovery procedure before changing processing. They cannot be inferred from a success response alone.']
  },
  {
    id: 'migration', title: 'The totals match. The migration does not.', category: 'Migration reconciliation',
    brief: 'A fictional migration report says source and target totals are both 1,500.00 EUR. The reviewer has approved the batch using only that total.',
    objective: 'Compare records by their stable keys. Decide whether the matching grand total is sufficient to accept the migration.',
    evidence: [
      { id: 'A', title: 'Source extract', intro: 'The cut-off is identical on both sides. Every listed open item should migrate exactly once with the same key and amount. There is one currency and no rounding rule.', columns: ['Stable item key', 'Open amount', 'Currency'], rows: [['item-a', '500.00', 'EUR'], ['item-b', '300.00', 'EUR'], ['item-c', '700.00', 'EUR']] },
      { id: 'B', title: 'Target extract', intro: 'There are no authorised exclusions, aggregation rules, renumberings, or offsets in this exercise.', columns: ['Stable item key', 'Open amount', 'Currency'], rows: [['item-a', '500.00', 'EUR'], ['item-b', '400.00', 'EUR'], ['item-d', '600.00', 'EUR']] },
      { id: 'C', title: 'Acceptance report', intro: 'This report groups only by currency. It does not join on the item key or compare individual records.', columns: ['Measure', 'Source', 'Target', 'Status'], rows: [['Row count', '3', '3', 'Equal'], ['Total EUR', '1,500.00', '1,500.00', 'Equal']] }
    ],
    calculation: { label: 'How many distinct item keys fail reconciliation?', suffix: 'keys', expected: 3, explanation: 'Three keys fail: item-b differs by +100 EUR, item-c is missing (−700 EUR), and item-d is unexpected (+600 EUR). Their signed differences sum to 0 EUR.' },
    cause: { label: 'Which conclusion is supported?', correct: 'offset', options: [['equal', 'Matching counts and totals establish a correct migration.'], ['offset', 'Different record-level errors offset each other in the grand total.'], ['rounding', 'The mismatch is explained by currency rounding.']], explanation: 'The stipulated mapping is one-to-one by stable key. item-a matches; the other three keys do not. No rounding or conversion explains these differences.' },
    citations: { expected: ['A', 'B', 'C'], explanation: 'A and B establish the key-level differences. C shows why the approval control failed to detect them.' },
    action: { label: 'What is the next supported action?', correct: 'hold', options: [['accept', 'Approve because both totals are 1,500 EUR.'], ['offset-entry', 'Add a balancing entry without investigating the rows.'], ['hold', 'Hold acceptance, isolate the three key-level exceptions, and have the mapping or load corrected before rerunning the comparison.']], explanation: 'An aggregate match cannot waive the one-to-one acceptance rule. Do not create another offset or reload blindly; investigate the exception records first.' },
    verification: { label: 'Which check supports acceptance after correction?', correct: 'outer', options: [['total', 'Recheck the grand total only.'], ['count', 'Recheck the row count only.'], ['outer', 'Check key uniqueness, missing and unexpected keys, and per-key amounts, then reconcile totals.']], explanation: 'A full key comparison must cover source-only and target-only records as well as matching keys. Duplicate-key checks prevent a later join from hiding multiplied rows.' },
    explanation: ['Only item-a reconciles. item-b is 100 EUR too high, item-c is absent, and item-d appears unexpectedly. The signed differences cancel, leaving a reassuring but insufficient total.', 'Treat the original total as one control, not the acceptance decision. Check unique keys first, compare their full union, classify exceptions, and retain the record-level evidence.', 'In a real migration, agree the cut-off, approved mapping, rounding, exclusions, and aggregation rules before comparing. This exercise deliberately fixes those assumptions to make the result deterministic.']
  }
];
